# .github/workflows/push.yml
name: Pulumi Deploy
on:
  push:
    branches:
      - main

jobs:
  preview:
    name: Pulumi Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install npm packages
        run: |
          npm run install

      - name: Build the react packages
        run: |
          npm run build:react

      - name: Deploy Pulumi Changes
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Invalidate CloudFront
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: ./pulumi
        run: |
          aws cloudfront create-invalidation --distribution-id $(pulumi stack output cfDistributionId) --paths '/*'
